package com.group10.sparkysbank.model;


// default package
// Generated Oct 25, 2014 12:37:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "sparkysbankdb")
public class Roles implements java.io.Serializable {

	private String type;
	

	public Roles() {
	}

	public Roles(String type) {
		this.type = type;
	}

	
	@Id
	@Column(name = "type", unique = true, nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	
}
