package com.group10.sparkysbank.model;

// default package
// Generated Oct 26, 2014 3:30:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "transaction_types", catalog = "sparkysbankdb")
public class TransactionTypes implements java.io.Serializable {

	private String idtransactionTypes;
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);

	public TransactionTypes() {
	}

	public TransactionTypes(String idtransactionTypes) {
		this.idtransactionTypes = idtransactionTypes;
	}

	public TransactionTypes(String idtransactionTypes,
			Set<Transactions> transactionses) {
		this.idtransactionTypes = idtransactionTypes;
		this.transactionses = transactionses;
	}

	@Id
	@Column(name = "idtransaction_types", unique = true, nullable = false, length = 45)
	public String getIdtransactionTypes() {
		return this.idtransactionTypes;
	}

	public void setIdtransactionTypes(String idtransactionTypes) {
		this.idtransactionTypes = idtransactionTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionTypes")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

}
