// default package
// Generated Oct 25, 2014 2:16:00 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "transactions", catalog = "sparkysbankdb")
public class Transactions implements java.io.Serializable {

	private int idtransactions;
	private TransactionTypes transactionTypes;
	private Integer amtInvolved;
	private String toAccountno;
	private Integer status;
	private Integer approvalNeeded;
	private Integer approved;

	public Transactions() {
	}

	public Transactions(int idtransactions) {
		this.idtransactions = idtransactions;
	}

	public Transactions(int idtransactions, TransactionTypes transactionTypes,
			Integer amtInvolved, String toAccountno,
			Integer status, Integer approvalNeeded, Integer approved) {
		this.idtransactions = idtransactions;
		this.transactionTypes = transactionTypes;
		this.amtInvolved = amtInvolved;
		this.toAccountno = toAccountno;
		this.status = status;
		this.approvalNeeded = approvalNeeded;
		this.approved = approved;
	}

	@Id
	@Column(name = "idtransactions", unique = true, nullable = false)
	public int getIdtransactions() {
		return this.idtransactions;
	}

	public void setIdtransactions(int idtransactions) {
		this.idtransactions = idtransactions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trans_type")
	public TransactionTypes getTransactionTypes() {
		return this.transactionTypes;
	}

	public void setTransactionTypes(TransactionTypes transactionTypes) {
		this.transactionTypes = transactionTypes;
	}

	
	@Column(name = "amt_involved")
	public Integer getAmtInvolved() {
		return this.amtInvolved;
	}

	public void setAmtInvolved(Integer amtInvolved) {
		this.amtInvolved = amtInvolved;
	}

	@Column(name = "to_accountno", length = 50)
	public String getToAccountno() {
		return this.toAccountno;
	}

	public void setToAccountno(String toAccountno) {
		this.toAccountno = toAccountno;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "approval_needed")
	public Integer getApprovalNeeded() {
		return this.approvalNeeded;
	}

	public void setApprovalNeeded(Integer approvalNeeded) {
		this.approvalNeeded = approvalNeeded;
	}

	@Column(name = "approved")
	public Integer getApproved() {
		return this.approved;
	}

	public void setApproved(Integer approved) {
		this.approved = approved;
	}

}
