package com.group10.sparkysbank.model;


// default package
// Generated Oct 25, 2014 12:37:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Useraccounts generated by hbm2java
 */
@Entity
@Table(name = "useraccounts", catalog = "sparkysbankdb")
public class Useraccounts implements java.io.Serializable {

	private String accountno;
	private String routingno;
	private String wiringno;
	private Date accountopendate;
	
	public Useraccounts() {
	}

	public Useraccounts(String accountno) {
		this.accountno = accountno;
	}

	public Useraccounts(String accountno, String routingno,
			String wiringno, Date accountopendate) {
		this.accountno = accountno;
		this.routingno = routingno;
		this.wiringno = wiringno;
		this.accountopendate = accountopendate;
		
	}

	@Id
	@Column(name = "accountno", unique = true, nullable = false, length = 50)
	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}


	@Column(name = "routingno", length = 45)
	public String getRoutingno() {
		return this.routingno;
	}

	public void setRoutingno(String routingno) {
		this.routingno = routingno;
	}

	@Column(name = "wiringno", length = 45)
	public String getWiringno() {
		return this.wiringno;
	}

	public void setWiringno(String wiringno) {
		this.wiringno = wiringno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "accountopendate", length = 10)
	public Date getAccountopendate() {
		return this.accountopendate;
	}

	public void setAccountopendate(Date accountopendate) {
		this.accountopendate = accountopendate;
	}


}
