package com.group10.sparkysbank.model;


// default package
// Generated Oct 25, 2014 12:37:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userinfo generated by hbm2java
 */
@Entity
@Table(name = "userinfo", catalog = "sparkysbankdb")
public class Userinfo implements java.io.Serializable {

	private int iduserinfo;
	private String firstname;
	private String middlename;
	private String lastname;
	private String username;
	private String salt;
	private String hash;
	private Date dob;
	private String address;
	private String identificationid;
	private Date expirydate;

	public Userinfo() {
	}

	public Userinfo(int iduserinfo) {
		this.iduserinfo = iduserinfo;
	}

	public Userinfo(int iduserinfo, String firstname,
			String middlename, String lastname, String username, String salt,
			String hash, Date dob, String address, String identificationid,
			Date expirydate) {
		this.iduserinfo = iduserinfo;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.username = username;
		this.salt = salt;
		this.hash = hash;
		this.dob = dob;
		this.address = address;
		this.identificationid = identificationid;
		this.expirydate = expirydate;
		
	}

	@Id
	@Column(name = "iduserinfo", unique = true, nullable = false)
	public int getIduserinfo() {
		return this.iduserinfo;
	}

	public void setIduserinfo(int iduserinfo) {
		this.iduserinfo = iduserinfo;
	}

	
	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "middlename", length = 45)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "salt", length = 65535)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "hash", length = 16777215)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "identificationid", length = 45)
	public String getIdentificationid() {
		return this.identificationid;
	}

	public void setIdentificationid(String identificationid) {
		this.identificationid = identificationid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expirydate", length = 10)
	public Date getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(Date expirydate) {
		this.expirydate = expirydate;
	}

	
}
